import { createContext, useContext, useEffect, useState, type ReactNode } from 'react';
import api from './services/api';

export const defaults = {
  hero: { slides: [
    { bg:'/images/together-stronger.jpg', tag:'Welcome to Our Community', title:'We Are <em>Together</em><br/>Stronger', sub:'A vibrant space where culture, creativity, and connection flourish every day.', primary:{href:'#about',label:'Discover Us'}, secondary:{href:'#events',label:'Upcoming Events'} },
    { bg:'/images/rhythm-meet-soul.jpg', tag:'Music & Arts', title:'Where <em>Rhythm</em><br/>Meets Soul', sub:'Live performances, art exhibitions, and cultural celebrations throughout the year.', primary:{href:'#activities',label:'Our Activities'}, secondary:{href:'#gallery',label:'View Gallery'} },
    { bg:'/images/move-thrive.jpg', tag:'Sports & Wellness', title:'Move. <em>Thrive.</em><br/>Belong.', sub:'From weekend sports leagues to yoga mornings — body and spirit united.', primary:{href:'#activities',label:'Join In'}, secondary:{href:'#donate',label:'Support Us'} },
    { bg:'/images/every-voice.JPG', tag:'Community Gatherings', title:'Every <em>Voice</em><br/>Matters Here', sub:'Monthly town halls, festivals, and shared meals that bring neighbours together.', primary:{href:'#events',label:'See Events'}, secondary:{href:'#articles',label:'Read Stories'} },
  ]},
  stats: { items:[{value:'2,400+',label:'Members'},{value:'18 Years',label:'of Service'},{value:'120+',label:'Events Per Year'},{value:'34',label:'Active Programmes'},{value:'6',label:'Cultural Chapters'}] },
  about: { eyebrow:'Who We Are', heading:'A Community Built on<br/><em>Heart</em> &amp; <em>Heritage</em>', paragraph1:'Al Burhaniya International was founded in March 2023 with a simple but powerful belief — that a neighbourhood is only as strong as its bonds. Over nearly two decades, we have grown into a thriving hub of culture, sport, arts, learning, and mutual care.', paragraph2:'We serve people of all ages, backgrounds, and abilities, offering free and low-cost programmes that enrich lives, foster friendships, and celebrate the rich tapestry of cultures that make us who we are.', imageMain:'/images/20231006_090317.jpg', imageTop:'/images/20221007_154440.jpg', imageBottom:'/images/20230812_230247.jpg', established:'March, 2023', buttonLabel:'Explore What We Do', buttonHref:'#activities', values:[{icon:'bi-people-fill',title:'Inclusivity',body:'Every person belongs here, without exception.'},{icon:'bi-stars',title:'Excellence',body:'We pursue quality in every programme we run.'},{icon:'bi-globe2',title:'Culture',body:'Celebrating diversity as our greatest strength.'},{icon:'bi-globe2',title:'Service',body:'Giving back to those who deserve and need the most.'}] },
  activities: { eyebrow:'What We Do', heading:'Activities &amp; Programmes', description:'From sunrise yoga to late-night music jams — there is something happening every single day of the week.', cards:[
    {large:true,cat:'Gatherings',bg:'https://images.unsplash.com/photo-1609234656388-0ff363383899?w=900&q=80',icon:'bi-people',title:'Community Gatherings',body:'Monthly town halls, seasonal festivals, potluck dinners, and neighbourhood watch meetings that keep us united.',tag:'Every Month'},
    {large:false,cat:'Music',bg:'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=700&q=80',icon:'bi-music-note-beamed',title:'Music',body:'Choir groups, instrument lessons, open-mic nights, and live concerts featuring local talent.',tag:'Weekly'},
    {large:false,cat:'Dance',bg:'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=700&q=80',icon:'bi-activity',title:'Dance',body:'Bollywood, hip-hop, classical, salsa, and contemporary — classes for all levels and ages.',tag:'3× per Week'},
    {large:false,cat:'Arts',bg:'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=700&q=80',icon:'bi-brush',title:'Arts & Crafts',body:'Painting, pottery, calligraphy, mosaics, and collaborative mural projects across the neighbourhood.',tag:'Tues & Sat'},
    {large:true,cat:'Sports',bg:'https://images.unsplash.com/photo-1547919307-1ecb10702e6f?w=900&q=80',icon:'bi-trophy',title:'Sports & Fitness',body:'Football, cricket, badminton, swimming, yoga, and annual community olympics. All skill levels welcome — fun is the only prerequisite.',tag:'Daily'},
    {large:false,cat:'Youth',bg:'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=700&q=80',icon:'bi-mortarboard',title:'Youth & Education',body:'After-school tutoring, coding clubs, leadership workshops, and mentorship for young minds.',tag:'Mon–Fri'},
    {large:false,cat:'Seniors',bg:'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=700&q=80',icon:'bi-heart-pulse',title:'Seniors Wellbeing',body:'Tea circles, gentle fitness, social lunches, digital literacy help, and wellbeing check-ins.',tag:'Daily'}] },
  events: {eyebrow:"What's On",heading:'Upcoming <em>Events</em>',buttonLabel:'View Full Calendar'},
  articles: {eyebrow:'Stories &amp; Insights',heading:'Latest <em>Articles</em>',buttonLabel:'All Articles'},
  gallery: {eyebrow:'Moments Captured',heading:'Our <em>Gallery</em>',description:'A glimpse into the life and spirit of Al Burhaniya.',buttonLabel:'View Full Gallery'},
  join: {heading:'Become a <em>Member</em> Today',description:'Join 2,400+ neighbours who are already part of the Al Burhaniya family. Free membership, full access.',primaryLabel:'Sign Up Free',primaryHref:'#contact',secondaryLabel:'Support Us Instead',secondaryHref:'#donate'},
  donate: {eyebrow:'Make a Difference',heading:'Your Support <em>Changes Lives</em>',description:'Every pound donated goes directly into our programmes, keeping them free and accessible for everyone — especially those who need them most.',impacts:[{amount:'£10',text:'Covers materials for one art workshop session',icon:'bi-gift'},{amount:'£25',text:"Funds a senior's wellbeing tea circle for a month",icon:'bi-people'},{amount:'£50',text:"Sponsors a young person's sports programme for a term",icon:'bi-trophy'},{amount:'£100+',text:'Helps sustain a full community programme for a season',icon:'bi-building-heart'}]},
  testimonials: {eyebrow:'Community Voices',heading:'What Our Members <em>Say</em>',items:[
    {quote:'"Al Burhaniya gave my children a place to belong when we first moved here. The dance classes and youth club changed everything for our family."',img:'https://randomuser.me/api/portraits/women/44.jpg',name:'Aisha Malik',role:'Member since 2019'},
    {quote:'"I was 70 and lonely after my husband passed. The seniors tea circle brought me back to life. I\'ve made friends I\'ll keep forever."',img:'https://randomuser.me/api/portraits/women/72.jpg',name:"Margaret O'Brien",role:'Member since 2020'},
    {quote:'"The cricket league was the reason I got fit, and the reason I met my best friends. Worth every Saturday morning."',img:'https://randomuser.me/api/portraits/men/32.jpg',name:'Ravi Sharma',role:'Member since 2018'},
    {quote:'"Running the community mural project was the most meaningful creative work I\'ve done. Al Burhaniya makes art feel purposeful."',img:'https://randomuser.me/api/portraits/women/28.jpg',name:'Elena Torres',role:'Volunteer Artist'},
    {quote:'"As a donor, I see exactly where my money goes. The annual impact report is transparent and the team is passionate. I give every year."',img:'https://randomuser.me/api/portraits/men/58.jpg',name:'James Holloway',role:'Supporter since 2017'}] },
  contact: {eyebrow:'Get In Touch',heading:"We'd Love to <em>Hear</em><br/>From You",description:'Whether you want to join, volunteer, partner, or just ask a question — our doors (and inboxes) are always open.',address:'164 Cheetham Hill Rd, Cheetham Hill, Manchester M8 8LQ',phone:'+44 74 5942 4579',email:'info@al-burhaniyainternational.co.uk',hours:'Mon–Fri 8am–9pm · Sat–Sun 9am–6pm',facebook:'',instagram:'',twitter:'',youtube:'',whatsapp:''},
  newsletter: {heading:'Stay in the Loop',description:'Get our monthly newsletter with event highlights, articles, and community news.'},
  innerPages: {events:{eyebrow:"What's On",heading:'Community <em>Events</em>',description:'From open-mic nights to annual festivals — something is always happening at Al Burhaniya. Find your next event below.',newsletterHeading:'Never Miss an Event',newsletterDescription:'Subscribe and get our monthly events newsletter delivered straight to your inbox.'},articles:{eyebrow:'Stories &amp; Insights',heading:'Community <em>Articles</em>',description:'Voices, stories, and insights from the heart of our community — written by members, volunteers, and staff.',newsletterHeading:'Stay in the Loop',newsletterDescription:'Get our monthly newsletter with article highlights, events, and community news.'},gallery:{eyebrow:'Moments Captured',heading:'Our <em>Gallery</em>',description:'A window into the life and spirit of Al Burhaniya — from festivals and sports days to quiet creative sessions and everything in between.',newsletterHeading:'Never Miss a Moment',newsletterDescription:'Subscribe to our newsletter and get the latest photos and event highlights delivered to your inbox.'}},
  navigation: {about:'About',activities:'Activities',events:'Events',articles:'Articles',gallery:'Gallery',contact:'Contact',donate:'Donate Now'},
  branding: {logo:'/logo.png',logoInvert:'/logo-invert.png',footerTagline:'A living community — rooted in heritage, growing toward a shared future.',footerRegistration:'Community Interest Company 14740901',footerExplore:'Explore',footerInvolved:'Get Involved',footerProgrammes:'Programmes',footerInfo:'Info',footerLinks:[{label:'Join as Member',href:'/#contact'},{label:'Volunteer',href:'/#contact'},{label:'Donate',href:'/#donate'},{label:'Partner With Us',href:'/#contact'},{label:'Hire Our Space',href:'/#contact'}],programmeLinks:[{label:'Youth Club',href:'/#activities'},{label:'Seniors Wellbeing',href:'/#activities'},{label:'Music & Arts',href:'/#activities'},{label:'Sports Leagues',href:'/#activities'},{label:'Cultural Events',href:'/#activities'}],infoLinks:[{label:'Privacy Policy',href:'#'},{label:'Cookie Policy',href:'#'},{label:'Safeguarding',href:'#'},{label:'Annual Report',href:'#'},{label:'Contact',href:'/#contact'}],copyright:'© 2026 Al Burhaniya Community Trust. All rights reserved.'},
};
export type SiteContent = typeof defaults;
const Context = createContext<SiteContent>(defaults);
export function mergeContent(data: Partial<SiteContent>): SiteContent {
  return Object.fromEntries(Object.entries(defaults).map(([key, value]) => [key, {...value, ...(data[key as keyof SiteContent] || {})}])) as SiteContent;
}
export function ContentProvider({children}:{children:ReactNode}) {
  const [content,setContent] = useState<SiteContent>(defaults);
  useEffect(()=>{api.get('/site-content').then(r=>setContent(mergeContent(r.data))).catch(()=>{});},[]);
  return <Context.Provider value={content}>{children}</Context.Provider>;
}
export const useContent = () => useContext(Context);
export const rich = (value:string) => ({__html: value.replace(/<(?!\/?(?:em|br)\b)[^>]*>/gi, '').replace(/<em\b[^>]*>/gi,'<em>').replace(/<br\b[^>]*>/gi,'<br/>').replace(/&(?!amp;|lt;|gt;|quot;|#39;)/g,'&amp;')});
export const imageUrl = (url:string) => !url ? '' : /^(https?:)?\/\//.test(url) ? url : (url.startsWith('/uploads/') || url.startsWith('/api/site-content/media/')) ? `${import.meta.env.VITE_API_URL?.replace(/\/api\/?$/, '') || 'http://localhost:5000'}${url}` : url;

export const safeHref = (href:string) => /^(https?:\/\/|mailto:|tel:|\/#|#|\/)/i.test(href) ? href : "#";
